server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: people-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/people/**
        - id: mail-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/mail/**